### ISSUE TITLE
Not working with JRE 14

### ISSUE THREAD

**Issue by tweenietomatoes** [oracle/nosql-examples#20]
I can't finish cluster_setup with JRE 14.

Oracle NoSQL requires java version 8 or higher. The java installation on
130.61.185.178 is 14.

**Comment by connelly38** [comment]
Fixed in latest version. Thanks!

**Comment by tweenietomatoes** [comment]
May i ask you, why Oracle NoSQL's Community Edition is version 18 and Enterprise is version 20.
Are they running on different version lines?

**Comment by mikebrey** [comment]
No changes have gone into CE.   We will be releasing an update to CE later on this summer.

**Comment by tweenietomatoes** [comment]
ok thanks for answering

**Comment by drubin999** [comment]
What was the reason for no updating CE for Q1?On May 8, 2020 9:30 AM, Michael Brey <notifications@github.com> wrote:
No changes have gone into CE.   We will be releasing an update to CE later on this summer.
