### ISSUE TITLE
How to declare multiple variables?

### ISSUE THREAD

**Issue by tweenietomatoes** [oracle/nosql-examples#22]
I am trying to do basic query.

My query is this as a preparedStatement:

'SELECT id, username, email, password FROM users WHERE username=$username AND password=$password'

I am trying to declare double variables. (https://docs.oracle.com/en/database/other-databases/nosql-database/19.5/sqlreferencefornosql/variable-declarations.html)

I am getting error when i declare like that:

DECLARE $username STRING;
DECLARE $password STRING;

in SELECT statement. 

I also tried DECLARE $username,$password STRING;

"message": "[ILLEGAL_ARGUMENT] PREPARE: Illegal Argument: Error: at (1, 26) no viable alternative at input 'DECLARE$usernameSTRING;DECLARE', at line 1:26\nrule stack: [parse, statement]"

**Comment by tweenietomatoes** [comment]
same as pl/sql done.

**Comment by drubin999** [comment]
Can you send us the error message?  I have working code that does the following:
"DECLARE $param1 STRING; $param2 STRING;\n" +
        "SELECT …"

**Comment by NoSQLGuy** [comment]
@tweenietomatoes the DECLARE syntax is as following :

variable_declaration ::= DECLARE (variable_name type_definition ";")+

You need to DECLARE only once and you need to separate variables via semicolon

So, the correct syntax would be 

DECLARE $username STRING; $password STRING; 
select ...

Give it try and let me know

**Comment by tweenietomatoes** [comment]
It was my mistake. I solved it by following pl/sql guide of yours.

Thanks for replies.

**Comment by NoSQLGuy** [comment]
Glad it worked for you. It would be useful to know what exactly is your use case for NoSQL DB. If possible, please drop me an email - anand dot chandak @oracle dot com (replace dot and spaces)
