### ISSUE TITLE
Plan 14 Ended with Errors

### ISSUE THREAD

**Issue by tweenietomatoes** [oracle/nosql-examples#23]
cluster_setup.sh

Oracle Linux 7 and 8. Single Node Installation. No cluster no replicates.

```
Executed plan 14, waiting for completion...

Plan 14 ended with errors. Use "show plan -id 14" for more information

Topology setup failed. It may be possible to get more information by
running /opt/oracle/nosql/kvstore/scripts/kvstore_admin.sh on X.X.X.X
```

I don't know what plan 14 is and i don't know how to get show plan -id 14. 
Is it OK to continue?

**Comment by connelly38** [comment]
If you run /opt/oracle/nosql/kvstore/scripts/kvstore_admin.sh on the node, and inside that do "show plan -id 14" there should be more information about the error.
In general, if this step fails then the setup will not be useable. So not Ok to continue. After looking more into the error, I suggest start the script again with '-f' option, to force it to stop any running services and try again.

**Comment by tweenietomatoes** [comment]
It seems like a connection issue.

**Comment by tweenietomatoes** [comment]
After it finished, i got TC.tar.gz no such file or directory.
It's just finished after that, TC.tar.gz is for extended tests i guess.

So i hope it's harmless.

**Comment by tweenietomatoes** [comment]
```
Copying test files to X.X.X.X..
TC.tar.gz                                     100% 9176     5.0MB/s   00:00
gzip: /tmp/TC.tar.gz: No such file or directory
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error copying test files: skipping extended test.

Cleaning up temporary files...

Cluster successfully created. Use the following parameters when
connecting to the service via java client:
-bash: Would: command not found

```

**Comment by tweenietomatoes** [comment]
it cleaned temporary files as well.

**Comment by connelly38** [comment]
yes, should be harmless.

**Comment by tweenietomatoes** [comment]
kvroot not added to path after installation.

**Comment by connelly38** [comment]
The script purposefully does not try to modify any user-specific settings like PATH. It does set up scripts in <kvroot>/scripts with paths set in them, such that executing any of those should work from enay environment.

**Comment by tweenietomatoes** [comment]
So i assume that after installation db is working on localhost. For single node port 5000 ?
Httpproxy is the way that we communicate. But first we need to create user and give it a permission. Done. But now i won't be able to connect to http proxy from outside. Getting
`[REQUEST_TIMEOUT] Authorization error: [operation timeout]: Failed to login to kvstore.  Operation timed out, see the cause `

Is httpproxy listening on localhost?

**Comment by tweenietomatoes** [comment]
Ok the reason is httpproxy is using self signed certificate.

**Comment by connelly38** [comment]
which kv-nn-nn tar/zip file are you using for your setup?
If you're using the latest ce edition (kv-ce-19.X), you can now use the stock cluster_setup script, which has just been updated. It will automatically configure the proxy for you.

**Comment by tweenietomatoes** [comment]
i don't know how to replace certificates of httpproxy. i would use let's encrypt.

**Comment by connelly38** [comment]
and yes, proxy setup with this script is done with a self-signed cert. Depending on the driver you're using you may have to specify options to allow it to agree to the cert. Most of the recent versions of java / go / python drivers all accept it by default. Not sure about the others.

**Comment by tweenietomatoes** [comment]
is it good idea to reverse proxy httpproxy ?

caddy web server got automatic tls feature.

**Comment by connelly38** [comment]
trying to configure httpproxy in any mode other than the default configuration (short of installing your own certs) will likely not work.

**Comment by connelly38** [comment]
Perhaps the docs at https://docs.oracle.com/en/database/other-databases/nosql-database/19.5/admin/configuring-proxy.html can help.

**Comment by tweenietomatoes** [comment]
which security file should i use to login sql shell?

adminlogin.security ?

**Comment by connelly38** [comment]
<kvroot>/scripts/kvstore_sql.sh should take care of that for you.

**Comment by tweenietomatoes** [comment]
so i am passing parameters to start_proxy.sh

**Comment by tweenietomatoes** [comment]
is it connecting to nodes through http proxy? because i saw the certificate that i gave during cluster_setup. i basically commented ssl certificate in config and restarted proxy.

instead i am reverse_proxying with caddy web server auto tls.

finally. it makes a good blog post.

**Comment by tweenietomatoes** [comment]
Well for clustering, i tried again on oracle cloud and it fails again :(. I thought its because Azure's Firewall first. Then i came to oracle cloud and let cluster_setup edit firewall settings.

I have 2 nodes, clean OCL 7, replicate factor 2

First netcat failed to verify connection but cluster_setup basically copied kv-*.tar.gz between nodes.

```
  Failure 1: 1/DeploySN sn2(10.0.0.17:5000) failed.: Problem connecting to the storage node agent, which may be caused by a security mismatch between the client and server, or by another network connectivity issue; nested exception is:
        java.rmi.ConnectIOException: Exception creating connection to: 10.0.0.17; nested exception is:
        java.net.SocketTimeoutException: connect timed out
Total tasks:           1
 Failed:               1
```
